name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  id-token: write # This is required for requesting the JWT
  contents: write  # This is required for actions/checkout

jobs:
  deploy:

    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/VoiceAuth
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10.X'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade -r requirements.txt
        pip install build
    - name: Build package
      run: |
        python -m pip install --upgrade -r requirements.txt
        python -m build --no-isolation
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
